services:
  - type: web
    name: roomloop-api
    env: node
    buildCommand: bash render-build.sh
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_ATLAS_URI
        sync: false
      - key: CLIENT_URL
        sync: false 