services:
  - type: web
    name: roomloop-api
    env: node
    buildCommand: npm install
    startCommand: bash render-start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_ATLAS_URI
        sync: false
      - key: CLIENT_URL
        sync: false 